[[CUTENSOR_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "2836a3815cc10be9884b78cd9396afa36bba6f47"
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "a499e078a4790e8f78486187a4a5b1ff0e4a2cdf2a7ff16b5f52ebc67ed7db69"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.2+0/CUTENSOR_CUDA102.v1.2.2.x86_64-linux-gnu.tar.gz"
[[CUTENSOR_CUDA102]]
arch = "powerpc64le"
git-tree-sha1 = "64b4d5df8dcc04841d373e7c639b93b4b023a0e1"
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "28816f7914fcfb76216dc7aa7de6dfbdead1b2b882e3517b39c873890ef54add"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.2+0/CUTENSOR_CUDA102.v1.2.2.powerpc64le-linux-gnu.tar.gz"
[[CUTENSOR_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "63d413d22160ae559e907d31dd66a804fe3e6be7"
os = "windows"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "49e3f07508b1bec5b77ebf8c6722d54b4f3e9e91ed395a0f393185340e33b7a5"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.2+0/CUTENSOR_CUDA102.v1.2.2.x86_64-w64-mingw32.tar.gz"
