[[CUTENSOR_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "03cdeb3db858287244c2530d75f0a845b90c48b4"
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "dbe99a6a5a2f68a2922e2c1006a451cad523a521004409fb80ca883303a85dbf"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.1+0/CUTENSOR_CUDA102.v1.2.1.x86_64-linux-gnu.tar.gz"
[[CUTENSOR_CUDA102]]
arch = "powerpc64le"
git-tree-sha1 = "029afc64d39bc2993604c9eb6a15ed8c32f21d57"
libc = "glibc"
os = "linux"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "44492dc223f5e7501fec90eb8f35ea68a7feb2284cfdc452d8ee533ddb28475d"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.1+0/CUTENSOR_CUDA102.v1.2.1.powerpc64le-linux-gnu.tar.gz"
[[CUTENSOR_CUDA102]]
arch = "x86_64"
git-tree-sha1 = "cbd0fa8210b55e659dcbd4a37194812c7edf6be7"
os = "windows"

    [[CUTENSOR_CUDA102.download]]
    sha256 = "c8e3e4be487245342ddf111fe487b54c6a2159b212d54277c80d455a184f9b6d"
    url = "https://github.com/JuliaBinaryWrappers/CUTENSOR_CUDA102_jll.jl/releases/download/CUTENSOR_CUDA102-v1.2.1+0/CUTENSOR_CUDA102.v1.2.1.x86_64-w64-mingw32.tar.gz"
